# Generated by Django 4.2.11 on 2024-05-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallent_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='comment',
        ),
    ]
